### ISSUE TITLE
StackOverflowError on old android devices

### ISSUE THREAD

**Issue by dimentiyinfo** [threerings/react#8]
Code like

`ValueView<SomeObj> view;`
`...`
`void crashReact() {`
`            for (int i = 0; i < 500; i++) {`
`                ValueView.Listener<SomeObj> omg = this::handleSomeObjChange;`
`                view.connectNotify(omg);`
`            }`
`}` 

will crash react compiled into android project, if was launched on android 4.4 for example:

03-12 19:58:05.371 3470-3470/my.pid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.pid, PID: 3470
    java.lang.StackOverflowError
        at react.Cons.insert(Cons.java:106)
        at react.Cons.insert(Cons.java:106)
        at react.Cons.insert(Cons.java:106)
        at react.Cons.insert(Cons.java:106)
        at react.Cons.insert(Cons.java:106)

This is due to recursion in Cons.insert(), Cons.remove() e t.c.

I'll place pull-request today

**Comment by samskivert** [comment]
Merged your PR. Thanks!
